logging:
  level:
    com.yunmi.app: DEBUG

spring:
  # druid 配置
  datasource:
    # 配置druid连接池
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-bp1p4hsj808930606io.mysql.rds.aliyuncs.com:3306/yunmi?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root_rhkj
    password: rhKJ1503409587

